server:
  port: 9999

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: true
    encoding: UTF-8

  datasource:
    url: jdbc:h2:/Users/wuyongyu/PycharmProjects/to_markdown/test
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    # schema: classpath:schema.sql

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  h2:
    console:
      enabled: true
      path: /db
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect




## markdown存储位置配置区:
markdown:
  filePath: ./mds/
